name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        runs-on: self-hosted
        steps:
          - name: Checkout code on Host
          - uses: actions/checkout@v4

          - name: Checkout submodules
            run : git submodule update --init --recursive

          - name: Run unit test in container
            run: |
              docker run --rm --platform linux/amd64 \
                -v $(pwd):/src \
                -w /src \
                cuaesd/aesd-autotest:24-unit-test \
                ./unit-test.sh
    full-test:
        runs-on: self-hosted
        steps:
          - name: Checkout code on Host
          - uses: actions/checkout@v4

          - name: Checkout submodules
            run : git submodule update --init --recursive

          - name: Run full test in container
            run: |
              docker run --rm --platform linux/amd64 \
                -v $(pwd):/src \
                -w /src \
                cuaesd/aesd-autotest:24-unit-test \
                ./full-test.sh
